---
- name: Register the Current Go Version (if Installed)
  shell: go version
  become: true
  become_user: "{{ username }}"
  register: go_version
  ignore_errors: yes
  changed_when: false
  failed_when: "'command not found' in go_version.stderr"

- include: go.yml
  when: go_version is failed or go_version.stdout != go_version_target